global:
  scrape_interval: 15s # Default is every 1 minute.

scrape_configs:
  - job_name: 'collector'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets:
          [
            'otel-collector:8889',
            'order-service:4000',
            'orchestrator-service',
            'inventory-service',
            'payment-service',
            'product-validation-service',
          ]
